// components/CardGame/CardSynopses.ts

export const CARD_SYNOPSES: string[] = [
    // 0. Achievements: King of Clubs
    "CERTIFICATIONS & AWARDS:\n" +
    "- CCNA. || CISCO NETWORK PROFESSIONAL.\n" +
    "- SECURITY+ & A1/2+ || COMPTIA.\n" +
    "- ACHIEVED A 99% GRADE AVERAGE FOR SOFTWARE ENGINEERING.\n" + // <-- ADDED \n here
    "- CYBERSECURITY ENGINEER || TRYHACKME.",
    
    // 1. Education: Queen of Clubs
    "EDUCATION:\n" +
    "- CERTIFIED SOFTWARE ENGINEER/DATA ENGINEER - HYPERIONDEV.\n" +
    "- CERTIFIED CYBERSECURITY SPECIALIST - EDUVOS. \n" +
    "- HAVARD CS50 FOR LAWYERS || HARVARD ONLINE.",
    
    // 2. Projects: Jack of Hearts
    "KEY PROJECTS:\n" +
    "- DISTRIBUTED COMPUTING AND SHARING OF RESOURCES ACCROSS A NETWORK.\n" +
    "- FULL-STACK PORTFOLIO WITH NEXT.JS, THREE.JS, SANITY.IO.\n" +
    "- CONTRIBUTIONS TO OPEN-SOURCE SELF-HOSTED PROXMOX SERVERS AND NODES.\n" +
    "- AI/ML WITH PYTORCH.\n" +
    "- M4N || A SELF-HOSTED HONEYPOT OS INTERACTING AS API FEEDING SIEM DATA.",
    
    // 3. Experience: Ace of Spades
    "PROFESSIONAL EXPERIENCE:\n" +
    "- DATA MONITOR/ENGINEER - PIPELINES, DATABASE SCHEMAS, DATA WRANGLING, BI-DASHBOARDS & STAKEHOLDER COMMUNICATION || SPINNAKER SOFTWARE 2025-2025\n" + // <-- ADDED \n here
    "- IT SUPPORT SPECIALIST (VOLUNTEER) - TICKET ASSIGNMENTS, STOCK ORDERING AND INVENTORY MANAGEMENT || CPOA 2022-2022",
    
    // 4. Blogsite: 10 of Hearts
    "TECHNICAL BLOG:\n" +
    "- A BLOGSITE TO DOCUMENT MY FINDINGS OR SOMETHING THAT I FOUND INTERESTING RATHER THAN SLOP POSTED ON LINKEDIN lol (i dont mean it please hire me).\n" +
    "- TOPICS FOCUSED ON EITHER VULNERABILITIES OR INTERESTING TOPICS AROUND SECURITY.\n" + // <-- Changed '; to .\' and fixed the double semicolon issue
    "- FOCUSING ON SHARING AND DEVELOPMENT OF KNOWLEDGE AROUND TECHNOLOGY.",
];